begin;

create table if not exists public.recipes (
    id bigint generated by default as identity primary key,
    name text not null,
    servings integer not null default 2 check (servings > 0),
    meal_type text not null default 'altro' check (meal_type in ('antipasto', 'primo', 'secondo', 'contorno', 'piatto_unico', 'colazione', 'merenda', 'dolce', 'altro')),
    use_automatically boolean not null default true,
    picture text,
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- Support existing recipe installations.
alter table public.recipes add column if not exists meal_type text not null default 'altro';
alter table public.recipes add column if not exists use_automatically boolean not null default true;
alter table public.recipes drop constraint if exists recipes_meal_type_check;
alter table public.recipes add constraint recipes_meal_type_check check (meal_type in ('antipasto', 'primo', 'secondo', 'contorno', 'piatto_unico', 'colazione', 'merenda', 'dolce', 'altro'));

create table if not exists public.recipe_ingredients (
    id bigint generated by default as identity primary key,
    recipe_id bigint not null references public.recipes(id) on delete cascade,
    item_prior_id bigint not null references public.item_prior(id),
    quantity double precision not null default 0,
    quantity_is_qb boolean not null default false,
    unit text not null default 'pz',
    sort_order integer not null default 0
);

-- Support existing installations and the special "q.b." quantity.
alter table public.recipe_ingredients add column if not exists quantity_is_qb boolean not null default false;
alter table public.recipe_ingredients drop constraint if exists recipe_ingredients_quantity_check;
alter table public.recipe_ingredients add constraint recipe_ingredients_quantity_check check (quantity_is_qb or quantity > 0);

create table if not exists public.meals (
    id bigint generated by default as identity primary key,
    name text not null,
    meal_date date not null,
    meal_type text not null check (meal_type in ('colazione', 'pranzo', 'cena')),
    people_count integer not null default 2 check (people_count > 0),
    completed_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.meals add column if not exists completed_at timestamptz;

create table if not exists public.meal_recipes (
    id bigint generated by default as identity primary key,
    meal_id bigint not null references public.meals(id) on delete cascade,
    recipe_id bigint not null references public.recipes(id),
    people_count integer not null default 2 check (people_count > 0),
    sort_order integer not null default 0,
    unique (meal_id, recipe_id)
);

alter table public.meal_recipes add column if not exists people_count integer not null default 2;
update public.meal_recipes mr set people_count = m.people_count
from public.meals m where m.id = mr.meal_id;
alter table public.meal_recipes drop constraint if exists meal_recipes_people_count_check;
alter table public.meal_recipes add constraint meal_recipes_people_count_check check (people_count > 0);

create table if not exists public.recipe_history (
    id bigint generated by default as identity primary key,
    recipe_id bigint not null references public.recipes(id) on delete cascade,
    cooked_on date not null,
    unique (recipe_id, cooked_on)
);

-- Snapshot delle righe di inventario consumate da un pasto, necessario per annullarlo.
create table if not exists public.meal_consumptions (
    id bigint generated by default as identity primary key,
    meal_id bigint not null references public.meals(id) on delete cascade,
    inventory_item_id bigint not null,
    item_snapshot jsonb not null,
    consumed_quantity double precision not null,
    consumed_unit text not null,
    created_at timestamptz not null default now()
);

-- Modello ricorrente manuale: viene copiato nella settimana solo su richiesta.
create table if not exists public.meal_defaults (
    id bigint generated by default as identity primary key,
    weekday integer not null check (weekday between 0 and 6),
    meal_type text not null check (meal_type in ('colazione', 'pranzo', 'cena')),
    name text not null,
    people_count integer not null default 2 check (people_count > 0),
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (weekday, meal_type)
);

create table if not exists public.meal_default_recipes (
    id bigint generated by default as identity primary key,
    meal_default_id bigint not null references public.meal_defaults(id) on delete cascade,
    recipe_id bigint not null references public.recipes(id),
    people_count integer not null default 2 check (people_count > 0),
    sort_order integer not null default 0,
    unique (meal_default_id, recipe_id)
);

alter table public.meal_default_recipes add column if not exists people_count integer not null default 2;
update public.meal_default_recipes dr set people_count = d.people_count
from public.meal_defaults d where d.id = dr.meal_default_id;
alter table public.meal_default_recipes drop constraint if exists meal_default_recipes_people_count_check;
alter table public.meal_default_recipes add constraint meal_default_recipes_people_count_check check (people_count > 0);

-- Strutture predisposte per proposta, compatibilità e notifiche future.
create table if not exists public.menu_plans (
    id bigint generated by default as identity primary key,
    week_start date not null unique,
    status text not null default 'draft' check (status in ('draft', 'proposed', 'accepted', 'dismissed')),
    version integer not null default 1,
    score double precision,
    explanation jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.menu_plan_meals (
    id bigint generated by default as identity primary key,
    menu_plan_id bigint not null references public.menu_plans(id) on delete cascade,
    meal_date date not null,
    meal_type text not null check (meal_type in ('colazione', 'pranzo', 'cena')),
    people_count integer not null default 2 check (people_count > 0),
    nutrition_snapshot jsonb,
    availability_snapshot jsonb,
    unique (menu_plan_id, meal_date, meal_type)
);

create table if not exists public.menu_plan_meal_recipes (
    id bigint generated by default as identity primary key,
    menu_plan_meal_id bigint not null references public.menu_plan_meals(id) on delete cascade,
    recipe_id bigint not null references public.recipes(id),
    sort_order integer not null default 0,
    recipe_snapshot jsonb,
    unique (menu_plan_meal_id, recipe_id)
);

create table if not exists public.ingredient_compatibilities (
    id bigint generated by default as identity primary key,
    requested_item_prior_id bigint not null references public.item_prior(id) on delete cascade,
    available_item_prior_id bigint not null references public.item_prior(id) on delete cascade,
    level text not null check (level in ('exact', 'partial', 'none')),
    quantity_factor double precision not null default 1 check (quantity_factor > 0),
    reason text,
    source text,
    is_manual boolean not null default false,
    created_at timestamptz not null default now(),
    unique (requested_item_prior_id, available_item_prior_id)
);

create table if not exists public.notification_deliveries (
    id bigint generated by default as identity primary key,
    menu_plan_id bigint references public.menu_plans(id) on delete cascade,
    week_start date not null,
    channel text not null check (channel in ('in_app', 'email', 'web_push')),
    status text not null default 'pending' check (status in ('pending', 'sent', 'failed', 'read')),
    sent_at timestamptz,
    error text,
    created_at timestamptz not null default now(),
    unique (week_start, channel)
);

create index if not exists idx_recipes_name on public.recipes(lower(name));
create index if not exists idx_recipe_ingredients_recipe on public.recipe_ingredients(recipe_id, sort_order);
create index if not exists idx_meals_date on public.meals(meal_date, meal_type);
create index if not exists idx_meal_recipes_meal on public.meal_recipes(meal_id, sort_order);
create index if not exists idx_recipe_history_recipe on public.recipe_history(recipe_id, cooked_on desc);
create index if not exists idx_meal_consumptions_meal on public.meal_consumptions(meal_id);
create index if not exists idx_meal_defaults_slot on public.meal_defaults(weekday, meal_type);
create index if not exists idx_meal_default_recipes_default on public.meal_default_recipes(meal_default_id, sort_order);
create index if not exists idx_menu_plan_meals_plan on public.menu_plan_meals(menu_plan_id, meal_date, meal_type);
create index if not exists idx_ingredient_compatibilities_requested on public.ingredient_compatibilities(requested_item_prior_id);

alter table public.recipes enable row level security;
alter table public.recipe_ingredients enable row level security;
alter table public.meals enable row level security;
alter table public.meal_recipes enable row level security;
alter table public.recipe_history enable row level security;
alter table public.meal_consumptions enable row level security;
alter table public.meal_defaults enable row level security;
alter table public.meal_default_recipes enable row level security;
alter table public.menu_plans enable row level security;
alter table public.menu_plan_meals enable row level security;
alter table public.menu_plan_meal_recipes enable row level security;
alter table public.ingredient_compatibilities enable row level security;
alter table public.notification_deliveries enable row level security;

drop policy if exists recipes_all on public.recipes;
drop policy if exists recipe_ingredients_all on public.recipe_ingredients;
drop policy if exists meals_all on public.meals;
drop policy if exists meal_recipes_all on public.meal_recipes;
drop policy if exists recipe_history_all on public.recipe_history;
drop policy if exists meal_consumptions_all on public.meal_consumptions;
drop policy if exists meal_defaults_all on public.meal_defaults;
drop policy if exists meal_default_recipes_all on public.meal_default_recipes;
drop policy if exists menu_plans_all on public.menu_plans;
drop policy if exists menu_plan_meals_all on public.menu_plan_meals;
drop policy if exists menu_plan_meal_recipes_all on public.menu_plan_meal_recipes;
drop policy if exists ingredient_compatibilities_all on public.ingredient_compatibilities;
drop policy if exists notification_deliveries_all on public.notification_deliveries;

create policy recipes_all on public.recipes for all to anon, authenticated using (true) with check (true);
create policy recipe_ingredients_all on public.recipe_ingredients for all to anon, authenticated using (true) with check (true);
create policy meals_all on public.meals for all to anon, authenticated using (true) with check (true);
create policy meal_recipes_all on public.meal_recipes for all to anon, authenticated using (true) with check (true);
create policy recipe_history_all on public.recipe_history for all to anon, authenticated using (true) with check (true);
create policy meal_consumptions_all on public.meal_consumptions for all to anon, authenticated using (true) with check (true);
create policy meal_defaults_all on public.meal_defaults for all to anon, authenticated using (true) with check (true);
create policy meal_default_recipes_all on public.meal_default_recipes for all to anon, authenticated using (true) with check (true);
create policy menu_plans_all on public.menu_plans for all to anon, authenticated using (true) with check (true);
create policy menu_plan_meals_all on public.menu_plan_meals for all to anon, authenticated using (true) with check (true);
create policy menu_plan_meal_recipes_all on public.menu_plan_meal_recipes for all to anon, authenticated using (true) with check (true);
create policy ingredient_compatibilities_all on public.ingredient_compatibilities for all to anon, authenticated using (true) with check (true);
create policy notification_deliveries_all on public.notification_deliveries for all to anon, authenticated using (true) with check (true);

commit;
