begin;

create table if not exists public.recipes (
    id bigint generated by default as identity primary key,
    name text not null,
    servings integer not null default 2 check (servings > 0),
    picture text,
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.recipe_ingredients (
    id bigint generated by default as identity primary key,
    recipe_id bigint not null references public.recipes(id) on delete cascade,
    item_prior_id bigint not null references public.item_prior(id),
    quantity double precision not null default 0,
    quantity_is_qb boolean not null default false,
    unit text not null default 'pz',
    sort_order integer not null default 0
);

-- Support existing installations and the special "q.b." quantity.
alter table public.recipe_ingredients add column if not exists quantity_is_qb boolean not null default false;
alter table public.recipe_ingredients drop constraint if exists recipe_ingredients_quantity_check;
alter table public.recipe_ingredients add constraint recipe_ingredients_quantity_check check (quantity_is_qb or quantity > 0);

create table if not exists public.meals (
    id bigint generated by default as identity primary key,
    name text not null,
    meal_date date not null,
    meal_type text not null check (meal_type in ('colazione', 'pranzo', 'cena')),
    people_count integer not null default 2 check (people_count > 0),
    completed_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.meals add column if not exists completed_at timestamptz;

create table if not exists public.meal_recipes (
    id bigint generated by default as identity primary key,
    meal_id bigint not null references public.meals(id) on delete cascade,
    recipe_id bigint not null references public.recipes(id),
    sort_order integer not null default 0,
    unique (meal_id, recipe_id)
);

create table if not exists public.recipe_history (
    id bigint generated by default as identity primary key,
    recipe_id bigint not null references public.recipes(id) on delete cascade,
    cooked_on date not null,
    unique (recipe_id, cooked_on)
);

-- Snapshot delle righe di inventario consumate da un pasto, necessario per annullarlo.
create table if not exists public.meal_consumptions (
    id bigint generated by default as identity primary key,
    meal_id bigint not null references public.meals(id) on delete cascade,
    inventory_item_id bigint not null,
    item_snapshot jsonb not null,
    consumed_quantity double precision not null,
    consumed_unit text not null,
    created_at timestamptz not null default now()
);

create index if not exists idx_recipes_name on public.recipes(lower(name));
create index if not exists idx_recipe_ingredients_recipe on public.recipe_ingredients(recipe_id, sort_order);
create index if not exists idx_meals_date on public.meals(meal_date, meal_type);
create index if not exists idx_meal_recipes_meal on public.meal_recipes(meal_id, sort_order);
create index if not exists idx_recipe_history_recipe on public.recipe_history(recipe_id, cooked_on desc);
create index if not exists idx_meal_consumptions_meal on public.meal_consumptions(meal_id);

alter table public.recipes enable row level security;
alter table public.recipe_ingredients enable row level security;
alter table public.meals enable row level security;
alter table public.meal_recipes enable row level security;
alter table public.recipe_history enable row level security;
alter table public.meal_consumptions enable row level security;

drop policy if exists recipes_all on public.recipes;
drop policy if exists recipe_ingredients_all on public.recipe_ingredients;
drop policy if exists meals_all on public.meals;
drop policy if exists meal_recipes_all on public.meal_recipes;
drop policy if exists recipe_history_all on public.recipe_history;
drop policy if exists meal_consumptions_all on public.meal_consumptions;

create policy recipes_all on public.recipes for all to anon, authenticated using (true) with check (true);
create policy recipe_ingredients_all on public.recipe_ingredients for all to anon, authenticated using (true) with check (true);
create policy meals_all on public.meals for all to anon, authenticated using (true) with check (true);
create policy meal_recipes_all on public.meal_recipes for all to anon, authenticated using (true) with check (true);
create policy recipe_history_all on public.recipe_history for all to anon, authenticated using (true) with check (true);
create policy meal_consumptions_all on public.meal_consumptions for all to anon, authenticated using (true) with check (true);

commit;
