begin;

create table if not exists public.item_prior (
    id bigint generated by default as identity primary key,
    name text not null unique,
    category text,
    typical_quantity double precision,
    typical_unit text,
    typical_quantity_pz double precision not null default 1 check (typical_quantity_pz > 0),
    typical_shelf_life_days integer,
    minimum_quantity double precision not null default 0 check (minimum_quantity >= 0),
    minimum_unit text not null default 'pz',
    inventory_display_unit text not null default 'measure' check (inventory_display_unit in ('pz', 'measure')),
    default_location text not null default 'dispensa' check (lower(default_location) in ('frigo', 'dispensa', 'freezer')),
    picture text,
    
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.inventory_items (
    id bigint generated by default as identity primary key,
    item_prior_id bigint not null references public.item_prior(id),
    quantity double precision not null default 1,
    unit text not null default 'pz',
    quantity_pz double precision,
    measure_quantity double precision,
    location text not null check (location in ('frigo', 'dispensa')),
    preparation_status text not null default 'none' check (preparation_status in ('none', 'cotto', 'aperto')),
    expiry_date date,
    expiry_estimated integer not null default 0,
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.inventory_items
    add column if not exists preparation_status text not null default 'none';

-- Quantità distinte: pezzi e quantità misurata. Le colonne legacy quantity/unit
-- restano per compatibilità con le installazioni già esistenti.
alter table public.item_prior
    add column if not exists inventory_display_unit text not null default 'measure';
alter table public.item_prior
    add column if not exists typical_quantity_pz double precision not null default 1;
alter table public.item_prior
    add column if not exists minimum_quantity double precision not null default 0;
alter table public.item_prior
    add column if not exists minimum_unit text not null default 'pz';
alter table public.item_prior
    drop constraint if exists item_prior_minimum_quantity_check;
alter table public.item_prior
    add constraint item_prior_minimum_quantity_check check (minimum_quantity >= 0);
alter table public.item_prior
    drop constraint if exists item_prior_minimum_unit_check;
alter table public.item_prior
    add constraint item_prior_minimum_unit_check check (minimum_unit in ('pz', 'g', 'ml', 'l', 'kg'));
alter table public.item_prior
    drop constraint if exists item_prior_inventory_display_unit_check;
alter table public.item_prior
    add constraint item_prior_inventory_display_unit_check
    check (inventory_display_unit in ('pz', 'measure'));
alter table public.inventory_items
    add column if not exists quantity_pz double precision;
alter table public.inventory_items
    add column if not exists measure_quantity double precision;
update public.inventory_items
set measure_quantity = case when lower(unit) = 'pz' then null else quantity end,
    quantity_pz = case when lower(unit) = 'pz' then quantity else quantity_pz end
where measure_quantity is null and quantity_pz is null;
update public.inventory_items i
set measure_quantity = i.quantity * p.typical_quantity
from public.item_prior p
where i.item_prior_id = p.id
  and lower(i.unit) = 'pz'
  and i.measure_quantity is null
  and p.typical_quantity is not null
  and lower(coalesce(p.typical_unit, 'pz')) <> 'pz';
update public.inventory_items i
set quantity_pz = (i.quantity *
    case when lower(i.unit) in ('kg', 'l') then 1000.0 else 1.0 end) /
    (p.typical_quantity * case when lower(p.typical_unit) in ('kg', 'l') then 1000.0 else 1.0 end)
from public.item_prior p
where i.item_prior_id = p.id
  and lower(i.unit) <> 'pz'
  and i.quantity_pz is null
  and p.typical_quantity is not null
  and lower(coalesce(p.typical_unit, 'pz')) <> 'pz';

update public.inventory_items
set preparation_status = 'none'
where preparation_status is null;

alter table public.inventory_items
    drop constraint if exists inventory_items_preparation_status_check;

alter table public.inventory_items
    add constraint inventory_items_preparation_status_check
    check (preparation_status in ('none', 'cotto', 'aperto'));

create table if not exists public.inventory_quantity_changes (
    id bigint generated by default as identity primary key,
    inventory_item_id bigint not null references public.inventory_items(id) on delete cascade,
    quantity double precision not null check (quantity <> 0),
    unit text not null default 'pz',
    changed_on date not null default current_date,
    changed_at timestamptz not null default now()
);

create table if not exists public.shopping_items (
    id bigint generated by default as identity primary key,
    item_prior_id bigint not null references public.item_prior(id),
    quantity double precision not null default 1,
    unit text not null default 'pz',
    quantity_pz double precision,
    measure_quantity double precision,
    target_location text not null check (target_location in ('frigo', 'dispensa')),
    notes text,
    created_at timestamptz not null default now()
);
alter table public.shopping_items add column if not exists quantity_pz double precision;
alter table public.shopping_items add column if not exists measure_quantity double precision;

create table if not exists public.items_history (
    id bigint generated by default as identity primary key,
    item_prior_id bigint not null references public.item_prior(id),
    inventory_item_id bigint references public.inventory_items(id) on delete set null,
    purchased_at timestamptz not null,
    quantity double precision not null default 1,
    unit text not null default 'pz',
    quantity_pz double precision,
    measure_quantity double precision,
    cost double precision,
    target_location text check (target_location in ('frigo', 'dispensa')),
    notes text,
    created_at timestamptz not null default now()
);
alter table public.items_history add column if not exists quantity_pz double precision;
alter table public.items_history add column if not exists measure_quantity double precision;

create index if not exists idx_item_prior_name on public.item_prior(lower(name));
create index if not exists idx_inventory_prior on public.inventory_items(item_prior_id);
create index if not exists idx_inventory_location on public.inventory_items(location);
create index if not exists idx_inventory_expiry on public.inventory_items(expiry_date);
create index if not exists idx_inventory_changes_day on public.inventory_quantity_changes(changed_on, inventory_item_id);
create index if not exists idx_shopping_prior on public.shopping_items(item_prior_id, unit, target_location);
create index if not exists idx_history_prior on public.items_history(item_prior_id, purchased_at);

alter table public.item_prior enable row level security;
alter table public.inventory_items enable row level security;
alter table public.inventory_quantity_changes enable row level security;
alter table public.shopping_items enable row level security;
alter table public.items_history enable row level security;

drop policy if exists item_prior_all on public.item_prior;
drop policy if exists inventory_items_all on public.inventory_items;
drop policy if exists inventory_quantity_changes_all on public.inventory_quantity_changes;
drop policy if exists shopping_items_all on public.shopping_items;
drop policy if exists items_history_all on public.items_history;

create policy item_prior_all
on public.item_prior
for all
to anon, authenticated
using (true)
with check (true);

create policy inventory_items_all
on public.inventory_items
for all
to anon, authenticated
using (true)
with check (true);

create policy inventory_quantity_changes_all
on public.inventory_quantity_changes
for all
to anon, authenticated
using (true)
with check (true);

create policy shopping_items_all
on public.shopping_items
for all
to anon, authenticated
using (true)
with check (true);

create policy items_history_all
on public.items_history
for all
to anon, authenticated
using (true)
with check (true);

commit;
