begin;

create table if not exists public.item_prior (
    id bigint generated by default as identity primary key,
    name text not null unique,
    category text,
    typical_quantity double precision,
    typical_unit text,
    typical_shelf_life_days integer,
    default_location text not null default 'dispensa' check (default_location in ('frigo', 'dispensa')),
    picture text,
    picture_source text,
    source_product_url text,
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.inventory_items (
    id bigint generated by default as identity primary key,
    item_prior_id bigint not null references public.item_prior(id),
    quantity double precision not null default 1,
    unit text not null default 'pz',
    location text not null check (location in ('frigo', 'dispensa')),
    expiry_date date,
    expiry_estimated integer not null default 0,
    notes text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.shopping_items (
    id bigint generated by default as identity primary key,
    item_prior_id bigint not null references public.item_prior(id),
    quantity double precision not null default 1,
    unit text not null default 'pz',
    target_location text not null check (target_location in ('frigo', 'dispensa')),
    notes text,
    created_at timestamptz not null default now()
);

create table if not exists public.items_history (
    id bigint generated by default as identity primary key,
    item_prior_id bigint not null references public.item_prior(id),
    inventory_item_id bigint references public.inventory_items(id) on delete set null,
    purchased_at timestamptz not null,
    quantity double precision not null default 1,
    unit text not null default 'pz',
    cost double precision,
    target_location text check (target_location in ('frigo', 'dispensa')),
    notes text,
    created_at timestamptz not null default now()
);

create index if not exists idx_item_prior_name on public.item_prior(lower(name));
create index if not exists idx_inventory_prior on public.inventory_items(item_prior_id);
create index if not exists idx_inventory_location on public.inventory_items(location);
create index if not exists idx_inventory_expiry on public.inventory_items(expiry_date);
create index if not exists idx_shopping_prior on public.shopping_items(item_prior_id, unit, target_location);
create index if not exists idx_history_prior on public.items_history(item_prior_id, purchased_at);

alter table public.item_prior enable row level security;
alter table public.inventory_items enable row level security;
alter table public.shopping_items enable row level security;
alter table public.items_history enable row level security;

drop policy if exists item_prior_all on public.item_prior;
drop policy if exists inventory_items_all on public.inventory_items;
drop policy if exists shopping_items_all on public.shopping_items;
drop policy if exists items_history_all on public.items_history;

create policy item_prior_all
on public.item_prior
for all
to anon, authenticated
using (true)
with check (true);

create policy inventory_items_all
on public.inventory_items
for all
to anon, authenticated
using (true)
with check (true);

create policy shopping_items_all
on public.shopping_items
for all
to anon, authenticated
using (true)
with check (true);

create policy items_history_all
on public.items_history
for all
to anon, authenticated
using (true)
with check (true);

commit;
